server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-d4dqad75r7bs73ftbsa0-a.oregon-postgres.render.com/aula15_gnz6
        username: aula15_gnz6_user
        password: QEPXukxmuUkPBRU7cch6wqa242BP5d5E
        driver-class-name: org.postgresql.Driver
        initialize: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres